export const LABELS = {
  GETTING_STARTED: "Getting Started",
  OVERVIEW: "Overview",
  INSTALLATION: "Installation",
  SUPPORT: "Support",
  CHANGE_LOG: "Change Log",
  DEVELOPMENT: "Development",
  FAQ: "FAQs",
  COLUMNS: "Column",
  ROW: "Row",
  SORTING: "Sorting",
  PAGINATION: "Pagination",
  TOOLTIP: "Tooltip",
  LOADER: "Loader",
  DEMO: "Demo",
  THEME_BUILDER: "Theme Builder",
  DOCUMENT: "Docs",
  FEATURES: "Features",
  TABLE_CLASS: "Table",
  POPOVER_CLASS: "PopOver",
  ARROW_PAGINATION_CLASS: "Arrow Pagination",
  TABLE_PAGINATION_CLASS: "Table Pagination",
  TOOLTIP_CLASS: "Tooltip",
  LOADER_CLASS: "Loader",
  CLASS_NAMES: "Class Names",
  CUSTOM_THEME: "Custom Theme",
  CSS_GUIDE: "CSS Guide",
  TABLE_PROPS: "Table",
  DARK_LIGHT_MODE: "Dark/Light Mode",
  CONTRIBUTION: "Contribution",
};

export const PATHS = {
  OVERVIEW: `/overview`,
  INSTALLATION: `/installation`,
  SUPPORT: `/support`,
  CHANGE_LOG: `/change-log`,
  DEVELOPMENT: `/development`,
  FAQ: `/faqs`,
  COLUMNS: `/column`,
  ROW: `/row`,
  SORTING: `/sorting`,
  PAGINATION: `/pagination`,
  TOOLTIP: `/tooltip`,
  LOADER: `/loader`,
  DEMO: `/demo`,
  THEME_BUILDER: `/theme-builder`,
  TABLE_CLASS: `/table-class`,
  POPOVER_CLASS: `/popover-class`,
  ARROW_PAGINATION_CLASS: `/arrow-pagination-class`,
  TABLE_PAGINATION_CLASS: `/table-pagination-class`,
  TOOLTIP_CLASS: `/tooltip-class`,
  LOADER_CLASS: `/loader-class`,
  CUSTOM_THEME: `/custom-theme`,
  CSS_GUIDE: `/css-guide`,
  TABLE_PROPS: `/table-props`,
  DARK_LIGHT_MODE: "/dark-light-mode",
  CONTRIBUTION: "/contribution",
};

export const KEY_LABELS = {
  MISCELLANEOUS: "Miscellaneous",
  GETTING_STARTED: "Getting Started",
  FEATURES: "Features",
  THEME: "Theme",
  PROPS: "Props",
};
